### ISSUE TITLE
Deliverables / Roadmap

### ISSUE THREAD

**Issue by WannesFransen1994** [WannesFransen1994/elixir-learning-materials#1]
This issue is to have an overview of deliverables of this project. This post will be edited as we complete them or new bullet points are added.

* [ ] License
* [ ] Introduction video on website (what is this project, why do we do it and how will we achieve it)
* [ ] Theoretical videos (with watermark!)
* [ ] Content-wise 1st priority: Elixir basics submodule/repository
* [ ] Content-wise 2nd priority: Phoenix framework submodule / repository
* [ ] In general better Readme.md files that explain how to use this repository

These are some extra thoughts, but for now will not work actively on them. These can be removed if deemed invaluable.
* [ ] Provide certificate
* [ ] Website on which we drop code and execute it (Like CodeWars)
* [ ] Embedded systems submodule / expert

Feel free to offer your thoughts below, every opinion / idea is appreciated.

**Comment by pdgonzalez872** [comment]
Excellent!

**Comment by WannesFransen1994** [comment]
Update: reordered Content-wise priorities

**Comment by WannesFransen1994** [comment]
*Update: Introduction video at [https://education.elixir.ucll.be/](https://education.elixir.ucll.be/)
*Update: some theory videos as well
*Update: content-wise elixir basics should be enough to get started. Some extras are still necessary
